name: Swift CustomList tests CI

on:
  push:
    branches: [ main, master ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10.1"
          disable-signature-verification: true

      - name: Run tests
        run: swift test --enable-test-discovery